export const homeCopy = {
  en: {
    kicker: 'Your community library',
    heroTitle: 'What will you discover today?',
    heroBody: 'Find your next book. Follow a new interest. Make it your own.',
    searchLabel: 'Search books',
    searchPlaceholder: 'Search for a book title…',
    searchAction: 'Search',
    browse: 'Browse books',
    guide: 'Show me around',
    topicsKicker: 'Follow your curiosity',
    topicsTitle: 'What would you like to read?',
    allTopics: 'See all books',
    explore: 'Explore',
    featuredKicker: 'From the library',
    featuredTitle: 'A little something for your next chapter',
    featuredAll: 'View the library',
    demoLabel: 'Demo catalogue',
    demoBody: 'These example books are shown while the live library is not connected.',
    loading: 'Finding books for you…',
    loadError: 'We could not load the library right now.',
    retry: 'Try again',
    emptyTitle: 'The library is getting ready.',
    emptyBody: 'There are no catalogue books to feature yet. Visit the library to browse when titles are added.',
    openLibrary: 'Open the library',
    availabilityUnknown: 'Ask the library desk about availability',
    available: (count: number) => count === 1 ? '1 copy available' : `${count} copies available`,
    sample: 'Example book',
    topics: { nature: 'Nature', stories: 'Stories', science: 'How things work' },
    topicDescription: { nature: 'Explore the world around us', stories: 'Meet people and places', science: 'Ask how and why' },
  },
  vi: {
    kicker: 'Thư viện cộng đồng của em',
    heroTitle: 'Hôm nay em muốn khám phá gì?',
    heroBody: 'Tìm cuốn sách tiếp theo. Khám phá điều em thích. Học theo cách của em.',
    searchLabel: 'Tìm sách',
    searchPlaceholder: 'Tìm theo tên sách…',
    searchAction: 'Tìm sách',
    browse: 'Xem sách',
    guide: 'Xem hướng dẫn',
    topicsKicker: 'Khám phá điều em thích',
    topicsTitle: 'Em muốn đọc gì?',
    allTopics: 'Xem tất cả sách',
    explore: 'Khám phá',
    featuredKicker: 'Từ thư viện',
    featuredTitle: 'Cho chương tiếp theo của em',
    featuredAll: 'Mở thư viện',
    demoLabel: 'Danh mục mẫu',
    demoBody: 'Các sách ví dụ hiển thị khi thư viện thật chưa được kết nối.',
    loading: 'Đang tìm sách cho em…',
    loadError: 'Chưa thể tải thư viện lúc này.',
    retry: 'Thử lại',
    emptyTitle: 'Thư viện đang chuẩn bị.',
    emptyBody: 'Chưa có sách trong danh mục để giới thiệu. Hãy mở thư viện khi sách được thêm vào.',
    openLibrary: 'Mở thư viện',
    availabilityUnknown: 'Hỏi bàn thư viện về tình trạng sách',
    available: (count: number) => `Còn ${count} bản`,
    sample: 'Sách ví dụ',
    topics: { nature: 'Thiên nhiên', stories: 'Truyện', science: 'Khoa học' },
    topicDescription: { nature: 'Khám phá thế giới quanh ta', stories: 'Gặp gỡ người và nơi chốn', science: 'Hỏi cách thức và lý do' },
  },
} as const;

export type HomeLanguage = keyof typeof homeCopy;
